paths:
  /api/productos:
    get:
      summary: Obtener todas los productos
      tags:
        - Productos
      responses:
        "200":
          description: Los productos se obtuvieron de forma correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor
  /api/productos/owner/{oid}:
    post:
      summary: Postear un producto nuevo
      tags:
        - Productos
      parameters:
        - name: oid
          in: path
          required: true
          description: oid es el id del usuario que quiere agregar en ese momento el producto
          schema:
            $type: number  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/PostProducts"
      responses:
        "200":
          description: Los productos se obtuvieron de forma correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor          
  /api/productos/{id}/:
    get:
      summary: Obtener productos por id
      tags:
        - Productos
      parameters:
        - name: id
          in: path
          required: true
          description: id es el id del producto
          schema:
            $type: number  
      responses:
        "200":
          description: El producto se obtuvo de forma correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor
  /api/productos/{id}:
    delete:
      summary: borrar productos por id
      tags:
        - Productos
      parameters:
        - name: id
          in: path
          required: true
          description: id es el id del producto a borrar
          schema:
            $type: number  
      responses:
        "200":
          description: El producto se elimino de forma correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor  
components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id del producto
        titulo:
          type: string
          description: nombre del producto
        descripcion:
          type: string
          description: descripcion del producto
        price:
          type: number
          description: precio del producto
        code:
          type: string
          description: codigo unico del producto
        thumbnail:
          type: String
          description: imagen del producto
      example:
        _id: ObjectId("gsa98273skjhgda8912")
        titulo: "Prs Multifoil"
        descripcion: "Guitarra Electrica"
        precio: 5000,
        code: "abc005"
        thumbnail: "wwww.cpom"
        stock: "50"
        status: true  
  requestBodies:
    PostProducts:
      type: object
      properties:
        titulo:
          type: string
          description: nombre del producto
        descripcion:
          type: string
          description: descripcion del producto
        price:
          type: number
          description: precio del producto
        code:
          type: string
          description: codigo unico del producto
        thumbnail:
          type: String
          description: imagen del producto
      example:
        titulo: "Prs Multifoil"
        descripcion: "Guitarra Electrica"
        precio: 5000,
        code: "abc005"
        thumbnail: "wwww.cpom"
        stock: 50,
        status: true